---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/manuelcc/api.manueldellagala.it/
    - /usr/local/cpanel/cgi-sys/sp-ea-php83 /home3/manuelcc/composer.phar self-update
    - /usr/local/cpanel/cgi-sys/sp-ea-php83 /home3/manuelcc/composer.phar update
    - /usr/local/cpanel/cgi-sys/sp-ea-php83 /home3/manuelcc/composer.phar install

