---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/manuelcc/api.manueldellagala.it/
    - /usr/local/bin/ea-php99 /home3/manuelcc/composer.phar self-update
    - /usr/local/bin/ea-php99 /home3/manuelcc/composer.phar update
    - /usr/local/bin/ea-php99 /home3/manuelcc/composer.phar install

